import os
import re
import datetime
from behave.parser import parse_file
from .helpers import ensure_dir, warn


def clean_filename(name):
    """Converts 'User Login' to 'user_login'"""
    return re.sub(r"[^a-zA-Z0-9]", "_", name).lower()


def confirm_overwrite(output_dir, args):
    """Handles the user prompt for overwriting existing docs."""
    if "-y" in args or "--yes" in args or not os.path.exists(output_dir):
        return True
    warn(f"⚠️  WARNING: Generating new docs will WIPE existing files in {output_dir}")
    response = input("   Continue? [y/N]: ").strip().lower()
    return response in ["y", "yes"]


def generate_rst_documentation(args):
    """Parses Gherkin files and generates individual .rst files for Sphinx."""
    features_dir = "./features"
    output_dir = "./docs/source/beast_docs/"
    ensure_dir(output_dir)

    if not confirm_overwrite(output_dir, args):
        print("   Aborted.")
        return

    rst_files = []
    print(f" Converting features from {features_dir} to RST...")

    for root, _, files in os.walk(features_dir):
        for file in files:
            if file.endswith(".feature"):
                path = os.path.join(root, file)
                try:
                    feature = parse_file(path)
                    filename = f"{clean_filename(feature.name)}.rst"
                    output_path = os.path.join(output_dir, filename)

                    with open(output_path, "w", encoding="utf-8") as f:
                        f.write(build_rst_content(feature))

                    rst_files.append(filename)
                    print(f"   - Generated {filename}")
                except Exception as e:  # pylint: disable=broad-exception-caught
                    print(f"   - Error parsing {file}: {e}")

    generate_index_file(output_dir, rst_files)


def build_rst_content(feature):
    """Constructs the RST string for a single feature."""
    lines = []

    # --- LEVEL 1 DEFENSE: THE WARNING HEADER ---
    lines.append(
        ".. ---------------------------------------------------------------------------"
    )
    lines.append("..  ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY  ⚠️")
    lines.append("..")
    lines.append(
        f"..  This file was generated by ArgoBEAST on {datetime.datetime.now().strftime('%Y-%m-%d')}."
    )
    lines.append("..  Any changes made here will be overwritten during the next build.")
    lines.append(
        "..  To update this documentation, edit the corresponding .feature file."
    )
    lines.append(
        ".. ---------------------------------------------------------------------------"
    )
    lines.append("")

    # 1. Feature Title (H1)
    lines.append("=" * len(feature.name))
    lines.append(feature.name)
    lines.append("=" * len(feature.name))
    lines.append("")

    # 2. Feature Description & Tags
    if feature.tags:
        tags_str = ", ".join([f"``@{t}``" for t in feature.tags])
        lines.append(f"**Tags:** {tags_str}")
        lines.append("")

    if feature.description:
        # Join description lines and clean whitespace
        desc = "\n".join(feature.description)
        lines.append(desc)
        lines.append("")

    # 3. Scenarios
    for scenario in feature.scenarios:
        lines.append("-" * len(scenario.name))
        lines.append(scenario.name)
        lines.append("-" * len(scenario.name))
        lines.append("")

        # Scenario Tags
        all_tags = list(set(feature.tags) | set(scenario.tags))
        if all_tags:
            # We use an 'admonition' box for tags to make them stand out
            lines.append(".. note::")
            lines.append(f"   **Tags:** {', '.join(all_tags)}")
            lines.append("")

        # Steps
        lines.append(".. list-table::")
        lines.append("   :widths: 10 90")
        lines.append("   :header-rows: 0")
        lines.append("")

        for step in scenario.steps:
            # Make keywords bold (Given, When, Then)
            lines.append(f"   * - **{step.keyword}**")
            lines.append(f"     - {step.name}")

        lines.append("")
        lines.append("")

    return "\n".join(lines)


def generate_index_file(output_dir, files):
    """Creates a table of contents for the features folder."""
    index_path = os.path.join(output_dir, "index.rst")
    with open(index_path, "w", encoding="utf-8") as f:
        f.write("Test Specifications\n")
        f.write("===================\n\n")
        # --- LEVEL 2 DEFENSE: THE CONTEXT ---
        f.write(".. warning::\n")
        f.write(
            "   This documentation is a **live snapshot** of the automation suite.\n"
        )
        f.write("   It is auto-generated from the Gherkin source code.\n\n")
        # ...
        f.write(".. toctree::\n")
        f.write("   :maxdepth: 1\n")
        f.write("   :caption: Features:\n\n")
        for file in sorted(files):
            # Remove extension for toctree
            f.write(f"   {file.replace('.rst', '')}\n")
