
services:
  selenium-grid:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "7900:7900" # NoVNC - lets users WATCH the tests in a browser
    shm_size: 2gb

  argobeast-runner:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - SE_REMOTE_URL=http://selenium-grid:4444/wd/hub
      - ARGO_ENV=container
      - IS_IN_LAB=True
    depends_on:
      - selenium-grid
    tty: true
    stdin_open: true
